### ISSUE TITLE
缺失导入的模块

### ISSUE THREAD

**Issue by Hahaha0310** [liangxuCHEN/irregular_packing#1]
在min_retange函数的第8行，“from my_rectpack_lib import base_tools”，并没有找到my_rectpack_lib包，也没有在其他.py文件中找到base_tools函数。请问是缺失了吗？

**Comment by liangxuCHEN** [comment]
不好意思，现在才看到你的信息，忘记把这个文件也包含进来，在这里有
https://github.com/liangxuCHEN/package_function/tree/master/my_rectpack_lib

**Comment by Hahaha0310** [comment]
Okay 非常感谢
